# Generated by Django 2.0.4 on 2018-04-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order_sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_Id', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('quantity_sum', models.PositiveIntegerField()),
                ('weight_sum', models.FloatField()),
                ('vol_sum', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_id', models.CharField(max_length=100)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sequence', models.PositiveIntegerField()),
                ('order_id', models.CharField(max_length=100)),
                ('sum_unique_item', models.PositiveIntegerField()),
                ('sum_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_vol', models.FloatField()),
                ('capacity_weight', models.FloatField()),
                ('rate_per_mile', models.FloatField()),
                ('fixed_cost', models.FloatField()),
                ('speed', models.FloatField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Distributor')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Van'),
        ),
        migrations.AddField(
            model_name='pick',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Route'),
        ),
        migrations.AddField(
            model_name='pick',
            name='van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Van'),
        ),
        migrations.AddField(
            model_name='order_summary',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Retailer'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Retailer'),
        ),
        migrations.AlterUniqueTogether(
            name='retailer',
            unique_together={('shop_id', 'distributor')},
        ),
    ]
