# Generated by Django 2.0.4 on 2018-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=20)),
            ],
        ),
    ]
