# Generated by Django 2.0.4 on 2018-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_summary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='van_id',
            field=models.CharField(default=1001, max_length=100),
            preserve_default=False,
        ),
    ]
